
name: Validate Documentation

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

  push:
    branches: ["main"]

jobs:
  validate-docs:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run docs check
        id: docs
        continue-on-error: true
        run: npm run check-docs

      - name: Generate report
        id: docs_info
        continue-on-error: true
        run: python3 .github/scripts/docs_report.py >> $GITHUB_OUTPUT
      
      - name: Leave lint information in comment
        if: ${{ steps.docs_info.outputs.message }}
        continue-on-error: ${{ steps.docs.outcome == 'success' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: 'docs_info'
          message: ${{ steps.docs_info.outputs.message }}

      - name: Check failure
        if: ${{ steps.docs_info.outputs.message }}
        run: exit 1
