
name: Format

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

  push:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Format
        run: npm run check-format
