
name: Test Build

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]
  
  push:
    branches: ["main"]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Ensure build
        run: npm run build
